### PR TITLE
Updated Python versions - Python 3.13

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #15

### CODE REVIEW

**Review by niccokunzmann — CHANGES_REQUESTED** [review]
@Brijeshthummar02 Thanks for the pull request! I really appreciate this.
I added a few comments - could you have a look and tell me what you think?

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
:tada: it shows up:

grafik

**Comment by Brijeshthummar02** [comment]
@niccokunzmann good to work with the repo.

**Pull request merged**
